### PR TITLE
Fix/pd 1314

### PR DESCRIPTION
**Pull request by sergiulucaci**
https://illuminate.atlassian.net/browse/PD-1314

### CODE REVIEW

**Review by andreeimiron — APPROVED** [review]

**Comment by sergiulucaci** [comment]
@andreeapescar any concern here?

**Comment by sergiulucaci** [comment]
@andreeapescar let's not merge it yet. It seems this breaks `./scripts/watch --scope ${package}` command. I get `error: unknown option '--sourcemaps'`. Will investigate and come back with an update.

**Comment by sergiulucaci** [comment]
@andreeapescar this should be ready now - you can run it locally also and see if it works for you.

**Comment by sergiulucaci** [comment]
@andreeimiron @andreeapescar this is ready to be merged now

**Comment by sergiulucaci** [comment]
Unfortunately not all packages will run on dev using `next@^12.1.0` because of this issue: https://github.com/vercel/next.js/issues/19936 (mask-markup for instance works while graphing doesn’t). We import mathquill.css like that in `@pie-framework/mathquill`. I suggest to stick with `next@9.5.3` (as @andreeimiron suggested) until they fix this: https://github.com/vercel/next.js/discussions/27953 

Also, updated `@pie-framework/build-helper@^5.2.9` as @andreeimiron / @andreeapescar suggested. 

Any thoughts?

**Pull request merged**
